### ISSUE TITLE
jest instructions not working

### ISSUE THREAD

**Issue by KeithWhatling** [scottdurow/building-power-apps-js-webresources#3]
![image](https://user-images.githubusercontent.com/55260385/122379973-4b791000-cf5f-11eb-80a1-af70f3268329.png)
The jest commands don't seem to do anything the just return  "'jest' is not recognized as an internal or external command,
operable program or batch file." 

I tried via NPM but we have not added any tests to package.json from what I can tell.

**Comment by scottdurow** [comment]
Thanks @KeithWhatling  - I've updated to include installing jest globally and the addition of the test script in package.json - https://github.com/scottdurow/building-power-apps-js-webresources/commit/1f385e9b7643fb34e116a30d60a5076b42cd7bfa
